from datetime import date
from typing import Protocol, runtime_checkable


@runtime_checkable
class Notifier(Protocol):
    def send_messages(self, messages: list[str]) -> None: ...


@runtime_checkable
class PortfolioReader(Protocol):
    def fetch(self) -> dict: ...
    def fetch_summary(self) -> dict: ...
    def build_holdings(self, data: dict) -> tuple: ...
    def build_totals(self, data: dict) -> dict: ...


@runtime_checkable
class MemoryReader(Protocol):
    def read_file(self, path: str) -> str: ...
    def last_n_entries(self, path: str, n: int) -> str: ...
    def append_entry(self, path: str, content: str) -> None: ...
    def resolve(self, filename: str) -> str: ...


@runtime_checkable
class TransactionLog(Protocol):
    def append(self, ticker: str, action: str, detail: str, reason: str = "") -> None: ...
    def entries_since(self, since: date) -> str: ...
